stages:
- test
- deploy
osx:
    stage: test
    script:
      - atbuild
      
    tags:
      - xcodeselect8
      - openswift
      - atbuild

linux:
    stage: test
    script:
      - apt-get update
      - apt-get install atbuild -y
      - atbuild

    tags:
      - autoscale-linux
    image: drewcrawford/buildbase:latest

docs:
    stage: test
    script:
      - cd docs
      - make html
      - make dashdoc

    artifacts:
      paths:
        - docs/_build/html
        - docs/_build/StandBack.docset

    tags:
      - autoscale-linux
    image: drewcrawford/anarchy-sphinx:latest

deploydocs:
  stage: deploy
  image: python:latest
  dependencies:
    - documentation
  script:
  - pip install awscli
  - aws s3 cp docs/_build/html/ s3://$DOC_BUCKET_NAME/ --recursive --acl "public-read"

  when: manual
  variables:
    DOC_BUCKET_NAME: "standback-docs.sealedabstract.com"
  tags:
    - autoscale-linux
